/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as FiltrosRouteImport } from './routes/filtros'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfiguratorRouteImport } from './routes/configurator'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcessoriosRouteImport } from './routes/acessorios'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcessoriosIndexRouteImport } from './routes/acessorios.index'
import { Route as ProdutosSlugRouteImport } from './routes/produtos.$slug'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as AcessoriosSlugRouteImport } from './routes/acessorios.$slug'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as BrandSlugIndexRouteImport } from './routes/brand.$slug.index'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as BrandSlugModelModelRouteImport } from './routes/brand.$slug.model.$model'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const FiltrosRoute = FiltrosRouteImport.update({
  id: '/filtros',
  path: '/filtros',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguratorRoute = ConfiguratorRouteImport.update({
  id: '/configurator',
  path: '/configurator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoriosRoute = AcessoriosRouteImport.update({
  id: '/acessorios',
  path: '/acessorios',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoriosIndexRoute = AcessoriosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcessoriosRoute,
} as any)
const ProdutosSlugRoute = ProdutosSlugRouteImport.update({
  id: '/produtos/$slug',
  path: '/produtos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoriosSlugRoute = AcessoriosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AcessoriosRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const BrandSlugIndexRoute = BrandSlugIndexRouteImport.update({
  id: '/brand/$slug/',
  path: '/brand/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandSlugModelModelRoute = BrandSlugModelModelRouteImport.update({
  id: '/brand/$slug/model/$model',
  path: '/brand/$slug/model/$model',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acessorios': typeof AcessoriosRouteWithChildren
  '/auth': typeof AuthRoute
  '/configurator': typeof ConfiguratorRoute
  '/contact': typeof ContactRoute
  '/favoritos': typeof FavoritosRoute
  '/filtros': typeof FiltrosRoute
  '/mcp': typeof McpRoute
  '/privacidade': typeof PrivacidadeRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/acessorios/$slug': typeof AcessoriosSlugRoute
  '/c/$slug': typeof CSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/acessorios/': typeof AcessoriosIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/brand/$slug/': typeof BrandSlugIndexRoute
  '/brand/$slug/model/$model': typeof BrandSlugModelModelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/configurator': typeof ConfiguratorRoute
  '/contact': typeof ContactRoute
  '/favoritos': typeof FavoritosRoute
  '/filtros': typeof FiltrosRoute
  '/mcp': typeof McpRoute
  '/privacidade': typeof PrivacidadeRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/acessorios/$slug': typeof AcessoriosSlugRoute
  '/c/$slug': typeof CSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/acessorios': typeof AcessoriosIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/brand/$slug': typeof BrandSlugIndexRoute
  '/brand/$slug/model/$model': typeof BrandSlugModelModelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acessorios': typeof AcessoriosRouteWithChildren
  '/auth': typeof AuthRoute
  '/configurator': typeof ConfiguratorRoute
  '/contact': typeof ContactRoute
  '/favoritos': typeof FavoritosRoute
  '/filtros': typeof FiltrosRoute
  '/mcp': typeof McpRoute
  '/privacidade': typeof PrivacidadeRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/acessorios/$slug': typeof AcessoriosSlugRoute
  '/c/$slug': typeof CSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/acessorios/': typeof AcessoriosIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/brand/$slug/': typeof BrandSlugIndexRoute
  '/brand/$slug/model/$model': typeof BrandSlugModelModelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/acessorios'
    | '/auth'
    | '/configurator'
    | '/contact'
    | '/favoritos'
    | '/filtros'
    | '/mcp'
    | '/privacidade'
    | '/products'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/acessorios/$slug'
    | '/c/$slug'
    | '/product/$handle'
    | '/produtos/$slug'
    | '/acessorios/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/brand/$slug/'
    | '/brand/$slug/model/$model'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/configurator'
    | '/contact'
    | '/favoritos'
    | '/filtros'
    | '/mcp'
    | '/privacidade'
    | '/products'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/acessorios/$slug'
    | '/c/$slug'
    | '/product/$handle'
    | '/produtos/$slug'
    | '/acessorios'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/brand/$slug'
    | '/brand/$slug/model/$model'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/acessorios'
    | '/auth'
    | '/configurator'
    | '/contact'
    | '/favoritos'
    | '/filtros'
    | '/mcp'
    | '/privacidade'
    | '/products'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/acessorios/$slug'
    | '/c/$slug'
    | '/product/$handle'
    | '/produtos/$slug'
    | '/acessorios/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/brand/$slug/'
    | '/brand/$slug/model/$model'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcessoriosRoute: typeof AcessoriosRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConfiguratorRoute: typeof ConfiguratorRoute
  ContactRoute: typeof ContactRoute
  FavoritosRoute: typeof FavoritosRoute
  FiltrosRoute: typeof FiltrosRoute
  McpRoute: typeof McpRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ProductsRoute: typeof ProductsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CSlugRoute: typeof CSlugRoute
  ProductHandleRoute: typeof ProductHandleRoute
  ProdutosSlugRoute: typeof ProdutosSlugRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  BrandSlugIndexRoute: typeof BrandSlugIndexRoute
  BrandSlugModelModelRoute: typeof BrandSlugModelModelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filtros': {
      id: '/filtros'
      path: '/filtros'
      fullPath: '/filtros'
      preLoaderRoute: typeof FiltrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configurator': {
      id: '/configurator'
      path: '/configurator'
      fullPath: '/configurator'
      preLoaderRoute: typeof ConfiguratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acessorios': {
      id: '/acessorios'
      path: '/acessorios'
      fullPath: '/acessorios'
      preLoaderRoute: typeof AcessoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acessorios/': {
      id: '/acessorios/'
      path: '/'
      fullPath: '/acessorios/'
      preLoaderRoute: typeof AcessoriosIndexRouteImport
      parentRoute: typeof AcessoriosRoute
    }
    '/produtos/$slug': {
      id: '/produtos/$slug'
      path: '/produtos/$slug'
      fullPath: '/produtos/$slug'
      preLoaderRoute: typeof ProdutosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acessorios/$slug': {
      id: '/acessorios/$slug'
      path: '/$slug'
      fullPath: '/acessorios/$slug'
      preLoaderRoute: typeof AcessoriosSlugRouteImport
      parentRoute: typeof AcessoriosRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/$slug/': {
      id: '/brand/$slug/'
      path: '/brand/$slug'
      fullPath: '/brand/$slug/'
      preLoaderRoute: typeof BrandSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/$slug/model/$model': {
      id: '/brand/$slug/model/$model'
      path: '/brand/$slug/model/$model'
      fullPath: '/brand/$slug/model/$model'
      preLoaderRoute: typeof BrandSlugModelModelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AcessoriosRouteChildren {
  AcessoriosSlugRoute: typeof AcessoriosSlugRoute
  AcessoriosIndexRoute: typeof AcessoriosIndexRoute
}

const AcessoriosRouteChildren: AcessoriosRouteChildren = {
  AcessoriosSlugRoute: AcessoriosSlugRoute,
  AcessoriosIndexRoute: AcessoriosIndexRoute,
}

const AcessoriosRouteWithChildren = AcessoriosRoute._addFileChildren(
  AcessoriosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcessoriosRoute: AcessoriosRouteWithChildren,
  AuthRoute: AuthRoute,
  ConfiguratorRoute: ConfiguratorRoute,
  ContactRoute: ContactRoute,
  FavoritosRoute: FavoritosRoute,
  FiltrosRoute: FiltrosRoute,
  McpRoute: McpRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ProductsRoute: ProductsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CSlugRoute: CSlugRoute,
  ProductHandleRoute: ProductHandleRoute,
  ProdutosSlugRoute: ProdutosSlugRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  BrandSlugIndexRoute: BrandSlugIndexRoute,
  BrandSlugModelModelRoute: BrandSlugModelModelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
