/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfiguratorRouteImport } from './routes/configurator'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BrandSlugRouteImport } from './routes/brand.$slug'
import { Route as BrandSlugModelModelRouteImport } from './routes/brand.$slug.model.$model'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguratorRoute = ConfiguratorRouteImport.update({
  id: '/configurator',
  path: '/configurator',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandSlugRoute = BrandSlugRouteImport.update({
  id: '/brand/$slug',
  path: '/brand/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandSlugModelModelRoute = BrandSlugModelModelRouteImport.update({
  id: '/model/$model',
  path: '/model/$model',
  getParentRoute: () => BrandSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/configurator': typeof ConfiguratorRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/brand/$slug': typeof BrandSlugRouteWithChildren
  '/category/$slug': typeof CategorySlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/brand/$slug/model/$model': typeof BrandSlugModelModelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/configurator': typeof ConfiguratorRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/brand/$slug': typeof BrandSlugRouteWithChildren
  '/category/$slug': typeof CategorySlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/brand/$slug/model/$model': typeof BrandSlugModelModelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/configurator': typeof ConfiguratorRoute
  '/contact': typeof ContactRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/brand/$slug': typeof BrandSlugRouteWithChildren
  '/category/$slug': typeof CategorySlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/brand/$slug/model/$model': typeof BrandSlugModelModelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/configurator'
    | '/contact'
    | '/products'
    | '/sitemap.xml'
    | '/brand/$slug'
    | '/category/$slug'
    | '/product/$handle'
    | '/brand/$slug/model/$model'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/configurator'
    | '/contact'
    | '/products'
    | '/sitemap.xml'
    | '/brand/$slug'
    | '/category/$slug'
    | '/product/$handle'
    | '/brand/$slug/model/$model'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/configurator'
    | '/contact'
    | '/products'
    | '/sitemap.xml'
    | '/brand/$slug'
    | '/category/$slug'
    | '/product/$handle'
    | '/brand/$slug/model/$model'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConfiguratorRoute: typeof ConfiguratorRoute
  ContactRoute: typeof ContactRoute
  ProductsRoute: typeof ProductsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BrandSlugRoute: typeof BrandSlugRouteWithChildren
  CategorySlugRoute: typeof CategorySlugRoute
  ProductHandleRoute: typeof ProductHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configurator': {
      id: '/configurator'
      path: '/configurator'
      fullPath: '/configurator'
      preLoaderRoute: typeof ConfiguratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/$slug': {
      id: '/brand/$slug'
      path: '/brand/$slug'
      fullPath: '/brand/$slug'
      preLoaderRoute: typeof BrandSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/$slug/model/$model': {
      id: '/brand/$slug/model/$model'
      path: '/model/$model'
      fullPath: '/brand/$slug/model/$model'
      preLoaderRoute: typeof BrandSlugModelModelRouteImport
      parentRoute: typeof BrandSlugRoute
    }
  }
}

interface BrandSlugRouteChildren {
  BrandSlugModelModelRoute: typeof BrandSlugModelModelRoute
}

const BrandSlugRouteChildren: BrandSlugRouteChildren = {
  BrandSlugModelModelRoute: BrandSlugModelModelRoute,
}

const BrandSlugRouteWithChildren = BrandSlugRoute._addFileChildren(
  BrandSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConfiguratorRoute: ConfiguratorRoute,
  ContactRoute: ContactRoute,
  ProductsRoute: ProductsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BrandSlugRoute: BrandSlugRouteWithChildren,
  CategorySlugRoute: CategorySlugRoute,
  ProductHandleRoute: ProductHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
